// <auto-generated />
using CondominioApp.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CondominioApp.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20251014002245_InserirDadosIniciais")]
    partial class InserirDadosIniciais
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.9");

            modelBuilder.Entity("CondominioApp.Models.Condomino", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Fracao")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Saldo")
                        .HasColumnType("TEXT");

                    b.Property<string>("Telefone")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Condominos");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Email = "joao@gmail.com",
                            Fracao = "A",
                            Nome = "João Silva",
                            Saldo = 150.75m,
                            Telefone = "912345678"
                        },
                        new
                        {
                            Id = 2,
                            Email = "maria@gmail.com",
                            Fracao = "B",
                            Nome = "Maria Costa",
                            Saldo = -25.00m,
                            Telefone = "913456789"
                        },
                        new
                        {
                            Id = 3,
                            Email = "ricardo@gmail.com",
                            Fracao = "C",
                            Nome = "Ricardo Alves",
                            Saldo = 0.00m,
                            Telefone = "914567890"
                        },
                        new
                        {
                            Id = 4,
                            Email = "ana@gmail.com",
                            Fracao = "D",
                            Nome = "Ana Pereira",
                            Saldo = 80.00m,
                            Telefone = "915678901"
                        },
                        new
                        {
                            Id = 5,
                            Email = "pedro@gmail.com",
                            Fracao = "E",
                            Nome = "Pedro Ramos",
                            Saldo = 20.50m,
                            Telefone = "916789012"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
